web/router.ex
defmodule Dispute.Router do
  use Dispute.Web, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", Dispute do
    pipe_through :browser # Use the default browser stack

    get "/", PageController, :index
    resources "/topics", TopicController do
      resources "/comments", CommentController
    end
  end

  # Other scopes may use custom stacks.
  scope "/api", Dispute, as: :api do
    pipe_through :api

    scope "/v1", Api.V1, as: :v1 do
      resources "/topics", TopicController, only: [:index, :show] do
        resources "/comments", CommentController
      end
    end
  end
end

lib/dispute/endpoint.ex
defmodule Dispute.Endpoint do
  use Phoenix.Endpoint, otp_app: :dispute

  socket "/socket", Dispute.UserSocket

  # Serve at "/" the static files from "priv/static" directory.
  #
  # You should set gzip to true if you are running phoenix.digest
  # when deploying your static files in production.
  plug Plug.Static,
    at: "/", from: :dispute, gzip: false,
    only: ~w(css fonts images js favicon.ico robots.txt)

  # Code reloading can be explicitly enabled under the
  # :code_reloader configuration of your endpoint.
  if code_reloading? do
    socket "/phoenix/live_reload/socket", Phoenix.LiveReloader.Socket
    plug Phoenix.LiveReloader
    plug Phoenix.CodeReloader
  end

  plug TrailingFormatPlug
  plug Plug.RequestId
  plug Plug.Logger

  plug Plug.Parsers,
    parsers: [:urlencoded, :multipart, :json],
    pass: ["*/*"],
    json_decoder: Poison

  plug Plug.MethodOverride
  plug Plug.Head

  # The session will be stored in the cookie and signed,
  # this means its contents can be read but not tampered with.
  # Set :encryption_salt if you would also like to encrypt it.
  plug Plug.Session,
    store: :cookie,
    key: "_dispute_key",
    signing_salt: "mO3WyZ5A"

  plug Dispute.Router
end

lib/dispute/repo.ex
defmodule Dispute.Repo do
  use Ecto.Repo, otp_app: :dispute
  use Scrivener, page_size: 2
end

web/models/comment.ex
defmodule Dispute.Comment do
  use Dispute.Web, :model

  schema "comments" do
    field :body, :string
    belongs_to :topic, Dispute.Topic

    timestamps()
  end

  @doc """
  Builds a changeset based on the `struct` and `params`.
  """
  def changeset(struct, params \\ %{}) do
    struct
    |> cast(params, [:body])
    |> validate_required([:body])
  end
end

web/models/topic.ex
defmodule Dispute.Topic do
  use Dispute.Web, :model

  schema "topics" do
    field :title, :string
    field :description, :string
    has_many :comments, Dispute.Comment

    timestamps()
  end

  @doc """
  Builds a changeset based on the `struct` and `params`.
  """
  def changeset(struct, params \\ %{}) do
    struct
    |> cast(params, [:title, :description])
    |> validate_required([:title, :description])
  end
end

web/controllers/api/v1/topic_controller.ex
defmodule Dispute.Api.V1.TopicController do
  use Dispute.Web, :controller

  alias Dispute.Topic

  def index(conn, _params) do
    topics = Repo.all(Topic)
    render(conn, "index.json", topics: topics)
  end

  def show(conn, %{"id" => id}) do
    topic = Repo.get!(Topic, id)
    topic = Repo.preload(topic, :comments)
    render(conn, "show.json", topic: topic)
  end
end

web/controllers/comment_controller.ex
defmodule Dispute.CommentController do
  use Dispute.Web, :controller

  alias Dispute.{Topic, Comment}

  def create(conn, %{"comment" => comment_params, "topic_id" => topic_id}) do
    topic = Repo.get(Topic, topic_id)
    changeset = Ecto.build_assoc(topic, :comments, body: comment_params["body"])

    case Repo.insert(changeset) do
      {:ok, _topic} ->
        conn
        |> put_flash(:info, "Post comment successful.")
        |> redirect(to: topic_path(conn, :show, topic))
        |> IO.inspect(topic)
      {:error, changeset} ->
        conn
        |> redirect(to: topic_path(conn, :show, topic))
        |> render(conn, "show.html", changeset: changeset)
        |> IO.inspect(topic)
    end
  end

  def delete(conn, %{"topic_id" => topic_id, "id" => id}) do
    comment = Repo.get!(Comment, id)
    topic = Repo.get(Topic, topic_id)

    # Here we use delete! (with a bang) because we expect
    # it to always work (and if it does not, it will raise).
    Repo.delete!(comment)

    conn
    |> put_flash(:info, "Comment deleted successfully.")
    |> redirect(to: topic_path(conn, :show, topic))
  end
end

web/controllers/page_controller.ex
defmodule Dispute.PageController do
  use Dispute.Web, :controller

  def index(conn, _params) do
    render conn, "index.html"
  end
end

web/controllers/topic_controller.ex
defmodule Dispute.TopicController do
  use Dispute.Web, :controller

  alias Dispute.{Topic, Comment}

  def index(conn, params) do
    # topics = Repo.all(Topic)
    page = Topic
           |> Repo.paginate(params)
    # render(conn, "index.html", topics: topics)
    render(conn, "index.html", topics: page.entries, page: page)

  end

  def new(conn, _params) do
    changeset = Topic.changeset(%Topic{})
    render(conn, "new.html", changeset: changeset)
  end

  def create(conn, %{"topic" => topic_params}) do
    changeset = Topic.changeset(%Topic{}, topic_params)

    case Repo.insert(changeset) do
      {:ok, _topic} ->
        conn
        |> put_flash(:info, "Topic created successfully.")
        |> redirect(to: topic_path(conn, :index))
      {:error, changeset} ->
        render(conn, "new.html", changeset: changeset)
    end
  end

  def show(conn, %{"id" => id}) do
    # topic = Topic
    #         |> Repo.get(id)
    #         |> Repo.preload(topic, :comments)
    topic = Repo.get!(Topic, id)
    topic = Repo.preload(topic, :comments)
    comment_changeset = Comment.changeset(%Comment{})
    render(conn, "show.html", topic: topic, comment_changeset: comment_changeset)
  end

  def edit(conn, %{"id" => id}) do
    topic = Repo.get!(Topic, id)
    changeset = Topic.changeset(topic)
    render(conn, "edit.html", topic: topic, changeset: changeset)
  end

  def update(conn, %{"id" => id, "topic" => topic_params}) do
    topic = Repo.get!(Topic, id)
    changeset = Topic.changeset(topic, topic_params)

    case Repo.update(changeset) do
      {:ok, topic} ->
        conn
        |> put_flash(:info, "Topic updated successfully.")
        |> redirect(to: topic_path(conn, :show, topic))
      {:error, changeset} ->
        render(conn, "edit.html", topic: topic, changeset: changeset)
    end
  end

  def delete(conn, %{"id" => id}) do
    topic = Repo.get!(Topic, id)

    # Here we use delete! (with a bang) because we expect
    # it to always work (and if it does not, it will raise).
    Repo.delete!(topic)

    conn
    |> put_flash(:info, "Topic deleted successfully.")
    |> redirect(to: topic_path(conn, :index))
  end
end

web/views/changeset_view.ex
defmodule Dispute.ChangesetView do
  use Dispute.Web, :view

  @doc """
  Traverses and translates changeset errors.

  See `Ecto.Changeset.traverse_errors/2` and
  `Dispute.ErrorHelpers.translate_error/1` for more details.
  """
  def translate_errors(changeset) do
    Ecto.Changeset.traverse_errors(changeset, &translate_error/1)
  end

  def render("error.json", %{changeset: changeset}) do
    # When encoded, the changeset returns its errors
    # as a JSON object. So we just pass it forward.
    %{errors: translate_errors(changeset)}
  end
end

web/views/comment_view.ex
defmodule Dispute.CommentView do
  use Dispute.Web, :view
end

web/views/error_view.ex
defmodule Dispute.ErrorView do
  use Dispute.Web, :view

  def render("404.html", _assigns) do
    "Page not found"
  end

  def render("500.html", _assigns) do
    "Internal server error"
  end

  # In case no render clause matches or no
  # template is found, let's render it as 500
  def template_not_found(_template, assigns) do
    render "500.html", assigns
  end
end

web/views/layout_view.ex
defmodule Dispute.LayoutView do
  use Dispute.Web, :view
end

web/views/page_view.ex
defmodule Dispute.PageView do
  use Dispute.Web, :view
end

web/views/topic_view.ex
defmodule Dispute.TopicView do
  use Dispute.Web, :view
  import Scrivener.HTML
end

web/templates/comment/new.html.eex
<h5 class="col s12 header">Add your comment</h5>
<%= form_for @comment_changeset, topic_comment_path(@conn, :create, @topic), fn f -> %>
  <div class="form-group">
    <div class="input-field col s12">
      <%= text_input f, :body, class: "validate" %>
      <%= label f, :body, class: "" %>
      <%= error_tag f, :body %>
    </div>
  </div>
  <div class="form-group">
    <%= submit "Submit", class: "btn btn-primary" %>
  </div>
<% end %>

web/templates/layout/app.html.eex
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Hello Dispute!</title>
    <link rel="stylesheet" href="<%= static_path(@conn, "/css/app.css") %>">
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.100.2/css/materialize.min.css">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/simplemde/latest/simplemde.min.css">
    <script type="text/javascript" src="https://code.jquery.com/jquery-3.2.1.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.100.2/js/materialize.min.js"></script>
    <script src="https://cdn.jsdelivr.net/simplemde/latest/simplemde.min.js"></script>
  </head>

  <body>
    <nav class="navbar-color gradient-45deg-light-blue-cyan">
      <div class="nav-wrapper container">
        <a href="/" class="brand-logo">Dispute</a>

        <ul class="right hide-on-med-and-down">
          <li>
            <a href="/topics">Topics</a>
          </li>
          <li>
            <a class="btn-floating btn-xs waves-effect waves-light">
              <i class="material-icons">fingerprint</i>
            </a>

          </li>
        </ul>
      </div>
    </nav>
    <main role="main">
      <div class="container">
        <%= if get_flash(@conn, :error) do  %>
          <div class="alert alert-danger alert-dismissible" role="alert">
            <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
            <%= get_flash(@conn, :error) %>
          </div>
        <% end %>
        <%= if get_flash(@conn, :info) do  %>
          <div class="alert alert-info alert-dismissible m-t-30" role="alert">
            <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
            <%= get_flash(@conn, :info) %>
          </div>
        <% end %>
          <%= render @view_module, @view_template, assigns %>
      </div>
    </main>
    <footer class="page-footer">
      <div class="container">
        <div class="row">
          <div class="col s12">
            <h5 class="white-text"></h5>
          </div>
        </div>
      </div>
      <div class="footer-copyright">
        <div class="container">
          <img src="https://files.readme.io/PKPqx8L9TJSAY2Bnmw7F_phoenixframework-logo-white@2x.png" alt="" class="right" style="max-height: 25px;">
          <div class="grey-text text-lighten-3 m-r-10 right">Powered by </div>
          <div class="grey-text text-lighten-4 left">2018 |</div>
          <a class="grey-text text-lighten-4 m-l-5 left" href="">MIT License</a>
        </div>
      </div>
    </footer>
    <script src="<%= static_path(@conn, "/js/app.js") %>"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
  </body>
</html>

web/templates/page/index.html.eex
<div class="jumbotron m-t-30">
  <h2><%= gettext "Welcome to %{name}", name: "Dispute!" %></h2>
  <p class="lead">A place where discussions live.</p>
</div>

web/templates/topic/edit.html.eex
<h2 class="col s12 header">
  Edit Topic: <span class="teal-text lighten-1"><%= @topic.title %></span>
  <%= link to: topic_path(@conn, :index), class: "btn right waves-effect waves-light m-t-30" do %>
    <i class="material-icons left">arrow_back</i>Back
  <% end %>
</h2>

<%= render "form.html", changeset: @changeset,
                        action: topic_path(@conn, :update, @topic) %>

web/templates/topic/form.html.eex
<%= form_for @changeset, @action, fn f -> %>
  <%= if @changeset.action do %>
    <div class="alert alert-danger">
      <p>Oops, something went wrong! Please check the errors below.</p>
    </div>
  <% end %>

  <div class="form-group">
    <div class="input-field col s12">
      <%= text_input f, :title, class: "validate" %>
      <%= label f, :title, class: "" %>
    </div>
    <%= error_tag f, :title %>
  </div>

  <div class="form-group">
    <div class="row">
      <div class="col s12">
        <%= label f, :description %>
        <%= textarea f, :description, class: "materialize-textarea", id: "body-editor" %>

      </div>
    </div>
    <%= error_tag f, :description %>
  </div>

  <div class="form-group">
    <%= submit "Submit", class: "btn btn-primary" %>
  </div>
<% end %>

web/templates/topic/index.html.eex
<h2 class="col s12 header">Topics
  <%= link to: topic_path(@conn, :new), class: "right btn-floating btn-xs waves-effect waves-light m-r-15 m-t-30" do %>
    <i class="material-icons dp48">add_circle</i>
  <% end %>
</h2>

<%= for topic <- @topics do %>
  <div class="card hoverable small">
    <div class="card-image relative">
      <img src="https://picsum.photos/1100/300/?random">
      <span class="card-title"><%= topic.title %></span>
      <div class="fixed-action-btn horizontal" style="position: absolute; top: 20px; right: 20px;" >
        <a class="btn-floating btn-large cyan">
          <i class="material-icons">menu</i>
        </a>
        <ul>
          <li>
            <%= link to: topic_path(@conn, :show, topic),
              class: "btn-floating yellow darken-1 tooltipped",
              style: "transform: scaleY(0.4) scaleX(0.4) translateY(0px) translateX(40px); opacity: 0;",
              data: [position: "top", delay: "50", tooltip: "Read more"] do %>
              <i class="material-icons dp48">comment</i>
            <% end %>
          </li>
          <li>
            <%= link to: topic_path(@conn, :edit, topic),
              class: "btn-floating blue tooltipped",
              style: "transform: scaleY(0.4) scaleX(0.4) translateY(0px) translateX(40px); opacity: 0;",
              data: [position: "top", delay: "50", tooltip: "Edit Topic"] do %>
              <i class="material-icons dp48">edit</i>
            <% end %>
          </li>
          <li>
            <%= link to: topic_path(@conn, :delete, topic),
              method: :delete,
              data: [confirm: "Are you sure?"],
              class: "btn-floating red tooltipped",
              style: "transform: scaleY(0.4) scaleX(0.4) translateY(0px) translateX(40px); opacity: 0;",
              data: [position: "top", delay: "50", tooltip: "Delete Topic"] do %>
              <i class="material-icons dp48">delete_forever</i>
            <% end %>
          </li>
        </ul>
      </div>
    </div>
    <div class="card-content">
      <%= link to: topic_path(@conn, :show, topic), class: "lead" do %>
          <%= raw(Earmark.as_html!(String.slice(topic.description, 0..100) <> "..."))%>
      <% end %>
    </div>
  </div>
<% end %>

<div class="text-center no-bg">
  <%= pagination_links @page %>
</div>

web/templates/topic/new.html.eex
<h2 class="col s12 header">
  New Topic
  <%= link to: topic_path(@conn, :index), class: "btn right waves-effect waves-light m-t-30" do %>
    <i class="material-icons left">arrow_back</i>Back
  <% end %>
</h2>

<%= render "form.html", changeset: @changeset,
                        action: topic_path(@conn, :create) %>

web/templates/topic/show.html.eex
<h2 class="col s12 header">
  <span class="teal-text lighten-1"><%= @topic.title %></span>
  <%= link to: topic_path(@conn, :index), class: "btn right waves-effect waves-light m-t-30" do %>
    <i class="material-icons left">arrow_back</i>Back
  <% end %>
</h2>

<div class="lead-show">
  <%= raw(Earmark.as_html!(@topic.description)) %>
</div>

<hr>
<%= for comment <- @topic.comments do %>
  <div class="col s12 m8 offset-m2 l6 offset-l3">
    <div class="card-panel grey lighten-5 z-depth-1">
      <div class="row valign-wrapper">
        <div class="col s1">
          <img src="https://picsum.photos/60/60/?random" alt="" class="circle responsive-img">
        </div>
        <div class="col s11">
          <span class="black-text">
            <%= comment.body %>
          </span>
        </div>
        <%= link to: topic_comment_path(@conn, :delete, @topic, comment),
          method: :delete,
          data: [confirm: "Are you sure?"],
          class: "btn-floating red tooltipped",
          data: [position: "top", delay: "50", tooltip: "Delete Comment"] do %>
          <i class="material-icons dp48">delete_forever</i>
        <% end %>
      </div>
    </div>
  </div>
<% end %>
<hr>
<%= render Dispute.CommentView, "new.html", conn: @conn, topic: @topic, comment_changeset: @comment_changeset %>